--
-- Script was generated by Devart dbForge Studio 2022 for SQL Server, Version 6.1.14.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 02.08.2023 15:23:54
-- Server version: 14.00.3294
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT Library.dbo.Books ON
GO
INSERT Library.dbo.Books(Id, Title, PublishedYear, CategoryID, AuthorID) VALUES (4, N'The Last Castle Rock Story', '1992-01-02 00:00:00.000', 7, 1)
INSERT Library.dbo.Books(Id, Title, PublishedYear, CategoryID, AuthorID) VALUES (7, N'The Da Vinci Code', '2003-01-02 00:00:00.000', 7, 2)
INSERT Library.dbo.Books(Id, Title, PublishedYear, CategoryID, AuthorID) VALUES (11, N'Harry Potter', '1990-01-01 00:00:00.000', 4, 5)
INSERT Library.dbo.Books(Id, Title, PublishedYear, CategoryID, AuthorID) VALUES (12, N'The Best of Me', '2010-08-02 00:00:00.000', 3, 3)
INSERT Library.dbo.Books(Id, Title, PublishedYear, CategoryID, AuthorID) VALUES (13, N'Throne of Glass', '2021-08-02 00:00:00.000', 4, 4)
GO
SET IDENTITY_INSERT Library.dbo.Books OFF
GO