--
-- Script was generated by Devart dbForge Studio 2022 for SQL Server, Version 6.1.14.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 02.08.2023 15:23:54
-- Server version: 14.00.3294
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT Library.dbo.Authors ON
GO
INSERT Library.dbo.Authors(AuthorID, FirstName, LastName, BirthDate) VALUES (1, N'Stephen ', N'King', '1947-09-21 00:00:00.000')
INSERT Library.dbo.Authors(AuthorID, FirstName, LastName, BirthDate) VALUES (2, N'Dan', N'Brown', '1964-06-22 00:00:00.000')
INSERT Library.dbo.Authors(AuthorID, FirstName, LastName, BirthDate) VALUES (3, N'Nicholas ', N'Sparks ', '1965-12-31 00:00:00.000')
INSERT Library.dbo.Authors(AuthorID, FirstName, LastName, BirthDate) VALUES (4, N'Sarah ', N'J. Maas.', '1986-03-05 00:00:00.000')
INSERT Library.dbo.Authors(AuthorID, FirstName, LastName, BirthDate) VALUES (5, N'Rowling', N'J.K', '1965-07-31 00:00:00.000')
GO
SET IDENTITY_INSERT Library.dbo.Authors OFF
GO