--
-- Script was generated by Devart dbForge Studio 2022 for SQL Server, Version 6.1.14.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 02.08.2023 15:23:54
-- Server version: 14.00.3294
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT Library.dbo.Reservations ON
GO
GO
SET IDENTITY_INSERT Library.dbo.Reservations OFF
GO